services:
  gateway:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - static:/static

  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - static:/app/build

  postgres:
    image: postgres:13
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database:
  static:
